#1 Sprint 9
naumich1984/java-filmorate pull request #5
Opened 2023-11-05 13:23 UTC by naumich1984

2023-11-05 21:13 UTC, avlin87 requested changes
Привет, Алексей,
Работа выглядит отлично. Мне понравилось. + Проверки выполняются.
Комментарии по pom файлу и по форматированию тестов.

2023-11-05 21:13 UTC, avlin87 commented on pom.xml
> +			<artifactId>spring-boot-starter-validation</artifactId>
У остальных spring boot зависимостей указана версия <version>${spring.boot.version}</version>
укажи, пожалуйста, её и тут.

2023-11-05 21:13 UTC, avlin87 commented on pom.xml
> +			<exclusions>
Если честно, я не понимаю зачем исключать зависимость и лично никогда не пользовался этим в мавене.
В грэйделе исключал один раз, когда в зависимостях подключились "неявно" два логгера и ломбок не мог определиться, который использовать.
Если не сложно, напиши, пожалуйста, зачем исключаешь ты. Очень интересно.

2023-11-05 21:13 UTC, avlin87 commented on pom.xml
> +			<artifactId>lombok</artifactId>
Добавь, пожалуйста, тэг с версией и версию ломбока вынеси, так же в проперти, как сейчас, у sprig boot
<version>${spring.boot.version}</version>.

Тут можно пользоваться (как и в Java коде) сочетанием клавиш:
например: поставишь тэг <version>0.0.0</version> (только с нормальной версией)
на значении тэга жмешь сочетание клавиш Ctrl + Alt + V. и идея автоматически вынесет значение в проперти, тебе останется поправить имя, если будет нужно.

2023-11-05 21:13 UTC, avlin87 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	void shouldGetAllUsers_whenGetRequest() {
Форматирование тестов:
принято отделять пустой строкой:
1) подготовка данных
2) выполнение тестовой операции (именно вызов метода)
3) assert

2023-11-06 08:22 UTC, naumich1984 commented on pom.xml
> +			<artifactId>spring-boot-starter-validation</artifactId>
Александр, приветствую! Добавил.

2023-11-06 08:28 UTC, naumich1984 commented on pom.xml
> +			<exclusions>
Идею исключения зависимости услышал на семинаре Практикума "Запись вебинара 9. Работа со Spring и Maven через IDEA + Postman. Владислав Гусев.mov и решил попробовать. В данным случае мы принудительно исключаем JUnit4, оставляя только JUnit5 - в будущем это может спасти от ситуации, когда приложение разрастется и при параллельной разработке разными командами часть тестов будет написано на JUnit4, а часть на JUnit5. И проблема точно возникнет при решении использовать Allure - там разный подход к интеграции разных версий JUnit.

2023-11-06 08:28 UTC, naumich1984 commented on pom.xml
> +			<artifactId>lombok</artifactId>
Исправил. Спасибо за совет по горячим клавишам!

2023-11-06 08:29 UTC, naumich1984 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	void shouldGetAllUsers_whenGetRequest() {
Исправил.

2023-11-07 05:16 UTC, avlin87 approved these changes
Хорошо, работу принимаю.

2023-11-07 05:18 UTC, merged