feat: sprint 11
naumich1984/java-filmorate pull request #7
Opened 2023-12-13 07:12 UTC by naumich1984

Добавлено сохранение состояния в БД

2023-12-13 19:43 UTC, avlin87 requested changes
Привет, Алексей,
Работа выглядит хорошо, смотри, пожалуйста, комментарии на github.

2023-12-13 19:43 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public ResponseEntity allGenres() {
В имя метода лучше добавить get, чтобы получилось `getAllGenres`.
Логика именования такая:
Метод что-то выполняет, по этому получившееся имя должно быть глаголом.

Поправь, пожалуйста, и в остальных местах.

2023-12-13 19:43 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String sql = "SELECT f.ID, f.NAME, f.DESCRIPTION, f.RELEASE_DATE, f.DURATION, \n"
Таблицы лучше соединять, а не выполнять запрос в запросе.
Поправь, пожалуйста этот и другие SQL запросы.
Пример:
```
    String sql = "SELECT " +
                 "   f.ID, " +
                 "   f.NAME, " +
                 "   f.DESCRIPTION, " +
                 "   f.RELEASE_DATE, " +
                 "   f.DURATION, " +
                 "   string_agg(gf.genre_id::text, ',') AS GENRES, " +
                 "   f.MPA_ID, " +
                 "   m.mpa_name " +
                 "FROM FILMS f " +
                 "INNER JOIN GENRES_FILMS gf ON f.ID = gf.FILM_ID " +
                 "INNER JOIN mpa m ON m.id = f.MPA_ID "
```

2023-12-13 19:43 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
>  public interface FilmStorage {
Для классов имплементаций интерфейсов было бы лучше создать дополнительный пакет impl.

2023-12-13 19:43 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        return allFilms().stream().filter(f -> f.getId() == filmId).findFirst().get();
В результате метода`findFirst()` мы получаем Optional.
Чтобы работать с ним верно давай преобразуем возвращаемый результат:
- Если isPresent() = true у получившегося Optional, то возвращаем объект из get()
- else возвращаем, например исключение, что объект не найден.

2023-12-13 19:43 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        int countTop = Optional.ofNullable(count).orElse(countTopFilm);
Проще будет воспользоваться
`int countTop = count != null ? count : countTopFilm;`

Optional предназначен для того, чтобы передавать значение между методами и способствовать добавлению проверок, что значение внутри него есть.
В остальных местах лучше пользоваться обычными средствами Java.

2023-12-13 19:43 UTC, avlin87 commented on src/test/java/ru/yandex/practicum/filmorate/UserDbStorageTest.java
> +class UserDbStorageTest {
Добавь, пожалуйста, пакет `storage`, чтобы структура пакетов тестового класса повторяла структуру пакетов тестируемого класса.

2023-12-14 13:33 UTC, naumich1984 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public FilmDbStorage(JdbcTemplate jdbcTemplate) {
Александр, привет. Спасибо за совет! Поправил.

2023-12-14 14:01 UTC, naumich1984 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
>  public interface FilmStorage {
Исправил.

2023-12-14 14:01 UTC, naumich1984 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        int countTop = Optional.ofNullable(count).orElse(countTopFilm);
Исправил. Спасибо за совет!

2023-12-14 14:01 UTC, naumich1984 commented on src/test/java/ru/yandex/practicum/filmorate/UserDbStorageTest.java
> +class UserDbStorageTest {
Исправил.

2023-12-14 14:53 UTC, naumich1984 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        return allFilms().stream().filter(f -> f.getId() == filmId).findFirst().get();
Исправил. Спасибо за совет!

2023-12-15 03:38 UTC, naumich1984 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String sql = "SELECT f.ID, f.NAME, f.DESCRIPTION, f.RELEASE_DATE, f.DURATION, \n"
Да, подзапросы не лучший вариант - исправил.

2023-12-15 05:40 UTC, avlin87 approved these changes
Работу принимаю.

2023-12-15 06:40 UTC, merged